name: Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # github-pages-deploy-action requires we set this
          persist-credentials: false
      
      - name: Restore the cached files
        uses: actions/cache@v2
        with:
          path: ~/.cargo/
          key: ${{ runner.os }}-pages-cargo
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
      
      - name: Install/Update cargo utils
        run: cargo install mdbook
      
      - name: Build The Book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/book_out
          CLEAN: true